### ISSUE TITLE
Backend - Performance optimization for Jobs page

### ISSUE THREAD

**Issue by Khristophor** [GCTC-NTGC/TalentCloud#640] opened 2019-01-18 14:13 UTC
# Description
Locally I noticed the following from the debugbar:

`377 statements were executed, 308 of which were duplicated, 69 unique`

My local jobs page has 61 unique entries, and it's executing five times as many duplicate queries when it builds the page. Need to look into how to build the queries for this data to avoid so many duplications.

# Required for Completion
Add/remove others as necessary for this specific task.
- [ ] Run Lighthouse (Chrome Dev Tools)
- [ ] Create pull request to `dev`
- [ ] Address issues found during peer review
- [ ] Have someone else accept pull request into `dev`

**Comment by gggrant** [comment] 2019-03-18 19:09
Duplicate of #781

**Closed by gggrant** 2019-03-18 19:09 UTC
Labels: Back-end, Medium Complexity
