### ISSUE TITLE
Manager Portal Application Review Localizations

### ISSUE THREAD

**Issue by xander-miller** [GCTC-NTGC/TalentCloud#789] opened 2019-03-08 19:41 UTC
Add Localization Strings to `{root}/en/manager/jobs/#/applications` view.

**Comment by xander-miller** [comment] 2019-03-18 14:32
Requires pattern for pushing lang files through to React components. Will talk to @tristan-orourke  about it.

**Comment by gggrant** [comment] 2019-03-28 15:48
Duplicate of #814

**Closed by gggrant** 2019-03-28 15:48 UTC
Labels: Front-end, Medium Complexity
