### ISSUE TITLE
Bug - Profile Information Not Saving

### ISSUE THREAD

**Issue by joshdrink** [GCTC-NTGC/TalentCloud#1328] opened 2019-08-23 18:02 UTC
# Description
This bug was reported by a user:

> I am trying to set up my profile and the Twitter handle field keeps defaulting to my email address. I tried adding my handle and leaving it blank, and each time I select Save Changes, it defaults back to my email address and gives me an error so I cannot proceed. I also lost my answer to the first question somewhere in the process of trying to fix the Twitter handle issue.

Sounds like Twig might be importing the wrong variable on page load? Perhaps it's actually not saving at all however.

**Comment by gobyrne** [comment] 2019-11-04 20:51
This sucks, but the profile needs a much bigger re-build, so I'm inclined to leave it for now.

**Comment by tristan-orourke** [comment] 2019-12-02 22:00
Duplicate of #1167

**Closed by tristan-orourke** 2019-12-02 22:00 UTC
Labels: Bug
