### ISSUE TITLE
Admin - Improvements to manager display table

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/TalentCloud#2130] opened 2019-11-22 17:23 UTC
Now that the number of managers using our platform is set to increase rapidly, we need some better sorting for Rosita bots.

Quick question, can you (devs) confirm this list does not include "Demo" manager accounts? (it should not)

Please make the following changes to /admin/manager table:
- Add department
- Add filter by department
- Remove "Role" column
- Can we copy all existing "upgraded manager" emails into the new Government email? All new managers should already have that filled in from now on before they get upgraded.
- If we did the previous, then we can get rid of the "email" column. (and just keep government email)
- Search also sucks here. Please change so that search ONLY searches the "Name" field. It should not be case sensitive though (Gray vaguely remembers there being a problem with Case, please let him know if that's still the case... pun...)

**Comment by Khristophor** [comment] 2019-11-22 19:47
We are only showing upgraded manager accounts in the admin view

**Comment by gggrant** [comment] 2019-11-29 13:05
And admins, on the Manager tab. Probably want to either keep 'Role' column or don't show admins.

Getting some of the searches working requires data restructuring, which will require significantly more effort than it might seem.

**Comment by tristan-orourke** [comment] 2019-12-02 21:45
Duplicate of #2177

**Closed by tristan-orourke** 2019-12-02 21:45 UTC
