### ISSUE TITLE
Bug - JPB Task delete button disappeared when # of key tasks over limit

### ISSUE THREAD

**Issue by rositak** [GCTC-NTGC/TalentCloud#1547] opened 2019-09-30 14:48 UTC
# Description
Delete icon disappeared for key tasks in one of the job posters when there are more key tasks than the recommended limit, but the icon reappeared again when the user used the JPB at another time.

# Images
Place image attachments here.

- [ ] Regression test written.

**Comment by tristan-orourke** [comment] 2019-12-02 21:58
Duplicate of #1590

**Closed by tristan-orourke** 2019-12-02 21:58 UTC
Labels: Bug, May be Resolved
