### ISSUE TITLE
Bug - Job Cards not showing Duration for new JPB postings

### ISSUE THREAD

**Issue by gggrant** [GCTC-NTGC/TalentCloud#1949] opened 2019-11-07 15:46 UTC
# Images
![duration.png](https://images.zenhubusercontent.com/5d9ce8bd5fc4fd0001589e3d/2ce5eff5-2914-43cc-9d20-7fa07789429d)

**Comment by tristan-orourke** [comment] 2019-11-19 14:46
Duplicate of #2041

**Closed by tristan-orourke** 2019-11-19 14:46 UTC
Labels: Bug
