### ISSUE TITLE
Bug - Applicant portal - 403 for closed jobs

### ISSUE THREAD

**Issue by rositak** [GCTC-NTGC/TalentCloud#3233] opened 2020-03-23 14:35 UTC
# Description
On the applicant portals, jobs with an id lower than 20 returns 403 when trying to access via direct link if I'm not logged in. It works when I'm logged in as an Admin (but doesn't work when I log in as a manager).

Example of URL that doesn't work: https://talent.canada.ca/en/jobs/18
Example of URL that works: https://talent.canada.ca/en/jobs/20

Both jobs have been posted before and are now closed. Any id between 2 - 18 falls under the closed jobs that don't work category.

# Technical Info

**Device:** Laptop
**Operating System:** Windows
**Browser:** Chrome

# Steps to Reproduce
Steps to reproduce the behavior. Example:
1. Without logging in, go to https://talent.canada.ca/en/jobs/18
2. See "403 Forbidden"
3. Now try https://talent.canada.ca/en/jobs/20
4. It works

- [ ] Regression test written.

**Comment by tristan-orourke** [comment] 2020-06-22 21:11
I just tested this after deploying to dev, and unfortunately this is still a problem.

**Comment by mnigh** [comment] 2020-11-10 23:50
@tristan-orourke Is a 403 status (unauthorized) not the expected behaviour here for any job posters (including the example referenced, [job #18](https://talent.canada.ca/en/jobs/18)) that have a status other than _live_, _assessment_, or _completed_? The `isPublic` method is referenced [in the view method of the JobPolicy class](https://github.com/GCTC-NTGC/TalentCloud/blob/b67df79ea10829d2f82c86e13e875913d4b4e5f2/app/Policies/JobPolicy.php#L13-L33) and takes care of the business logic for those who are not logged in.

**Comment by tristan-orourke** [comment] 2020-11-12 14:57
@mnigh That's right, that is expected. But I would think those jobs would have the status _completed_, do they not?

**Comment by mnigh** [comment] 2020-11-12 16:27
@tristan-orourke as discussed, perhaps these jobs have a status that isn't one of _live_, _assessment_, or _completed_ since they were created before the column was created.

**Comment by tristan-orourke** [comment] 2021-02-17 16:10
Solution seems to be changing status in database to completed

**Comment by gobyrne** [comment] 2021-04-08 18:51
@tristan-orourke did this not get fixed recently?

**Comment by tristan-orourke** [comment] 2021-04-08 18:55
@gobyrne We fixed most of them at least. I'll do one more check later to see if there any we missed, and close the issue for good.

**Comment by tristan-orourke** [comment] 2021-04-09 14:28
They've now all been fixed by modifying job_poster_status_id in the database.

**Closed by tristan-orourke** 2021-04-09 14:28 UTC
Labels: Back-end, Bug
