### ISSUE TITLE
Localization of Manager React Views

### ISSUE THREAD

**Issue by joshdrink** [GCTC-NTGC/TalentCloud#814] opened 2019-03-20 17:35 UTC
# Description
The new React-based views need a broader localization strategy, as well as localization proper.

## Criteria
- [x] A localization strategy has been decided on for React.
- [x] Manager facing React views have French copy.
- [ ] This task requires a unit test.

PR for this issue: #819

**Comment by gggrant** [comment] 2019-03-28 15:48
Duplicate of #814

**Comment by xander-miller** [comment] 2019-04-02 13:47
Working on this will PR #819

**Comment by xander-miller** [comment] 2019-04-04 16:08
PR #819 Ready for Review

**Closed** 2019-04-11 15:40 UTC
Labels: April 17th Priorities, Back-end, Front-end
