### ISSUE TITLE
Bug - Manager - Skill pop-up on Job Builder. Cannot scroll after pop-up resizes

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/TalentCloud#1597] opened 2019-10-02 19:18 UTC
# Description
Skill pop-up on Job Builder. Cannot scroll after pop-up resizes. This actually makes it impossible to click on the "submit" button.

# Steps to Reproduce
Steps to reproduce the behavior. Example:
1. Go to Skills step of the Job Poster Builder
2. Click on "Other Skill" drop down at the bottom of page. I actually did not get the same bug when I clicked on the suggested skills.
3. Click on the "add specificity" button under skill description
4. Try to scroll down on page to the "submit" button.

**Comment by tristan-orourke** [comment] 2019-10-03 15:14
Duplicate of #1582

**Closed by tristan-orourke** 2019-10-03 15:14 UTC
Labels: Bug
