### ISSUE TITLE
Applicant/Job Poster - Add info modals to "Telework" & "Remote work"

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/TalentCloud#374] opened 2018-10-17 14:35 UTC
# Description
Add an info button next to the titles "Telework" and "Remote work" on the job poster. This will bring up a modal with a small explanation of what it means.

# Images
![image](https://user-images.githubusercontent.com/16977254/47093985-4dabcf00-d1f8-11e8-962a-735e0b50056e.png)

# Required for Completion
Add/remove others as necessary for this specific task.
- [ ] Run Lighthouse (Chrome Dev Tools)
- [ ] Run WAVE Evaluation
- [ ] Browser Compatibility Check
- [ ] Update Translation Spreadsheet
- [ ] Does this affect configuration? (If so discuss with team)
- [ ] Create pull request to `dev`
- [ ] Address issues found during peer review
- [ ] Have someone else accept pull request into `dev`

**Comment by gobyrne** [comment] 2019-01-08 18:40
This is a duplicate of #417. Closing this issue

**Closed by gobyrne** 2019-01-08 18:40 UTC
Labels: FED, Task
