### ISSUE TITLE
Bug - User cannot submit job application

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/TalentCloud#2914] opened 2020-02-12 15:55 UTC
# Description
User can not submit application because "it says that Step 3 needs to be filled in". However, on Step 3 (skills checklist) "it has green checks on each part but at the top on the Steps Navigation bar, there is a red x even though the actual steps are filled up."

As Tristan suggests in the comments, we would like to update this error text to help applicants get through this.

**New Error text**
English:
Step 3 must be completed. If Step 3 appears complete, please check the skills page on your profile for duplicate entries. Multiple copies of a skill on your profile can also cause this error. We are working to resolve this issue.

French:
L'étape 3 doit être complet. Si l'étape 3 semble complet, veuillez consulter la page de compétences de votre profil pour les compétences en double. Des copies multiples d'une compétence sur votre profil peut également provoquer cette erreur. Nous travaillons pour résoudre ce problème.

**Comment by tristan-orourke** [comment] 2020-02-12 22:30
This is caused by the user having a duplicate skill declaration for one of the required criteria, with one of their declarations having an empty description and therefore being considered invalid.

Quick solution: Expand the error message from "Step 3 must be completed" to "Step 3 must be completed. If it looks complete, check to make sure you don't have duplicate skills on your profile, as this may cause errors."

Medium-term solution: Ensure its impossible to save duplicate skills, and go through the database manually to delete old duplicates.

Long-term solution: we make sure this kind of problem can't happen again in the new Timeline Application, but duplicates in the old data will no longer matter.

**Comment by gobyrne** [comment] 2020-02-14 13:22
Right, so this problem does just go away once we release Timeline Application. Then we should probably be full steam ahead on it then. Will investigate if the error message change is worthwhile.

**Comment by gobyrne** [comment] 2020-02-28 17:56
Reopening because it looks like this is happening to another user.

**Comment by tristan-orourke** [comment] 2020-03-03 15:07
Closing this in favour of creating a new issue (so as not to mess with velocity of previous sprints).

**Closed by tristan-orourke** 2020-03-03 15:07 UTC
Labels: Bug
