### ISSUE TITLE
Bug - Manager portal missing demo account banner on JPB

### ISSUE THREAD

**Issue by JasmitaChawla** [GCTC-NTGC/TalentCloud#1572] opened 2019-10-01 17:55 UTC
# Description
The job poster builder on the manager portal is missing the "This is a demo account. Click here to find out how to publish a job on Talent Cloud" banner on the top of the page.  

# Steps to Reproduce
1. Log on to the manager portal as a demo account user.
2. Go to "My Job Posters"
3. Click on "Create a New Poster"

# Images
![Capture3](https://user-images.githubusercontent.com/38079220/65986908-d8f69280-e452-11e9-8626-a2359ec0a21c.png)

- [ ] Regression test written.

**Comment by tristan-orourke** [comment] 2019-11-06 16:57
Closed, duplicate of #1856

**Closed by tristan-orourke** 2019-11-06 16:57 UTC
Labels: Bug
