### ISSUE TITLE
Feature - Applicant/Manager/Admin - Blog

### ISSUE THREAD

**Issue by JoshBeveridge** [GCTC-NTGC/TalentCloud#3898] opened 2020-06-16 16:34 UTC
# Description

There's been ongoing chatter about building a native blog on the application. @Khristophor and I have discussed it and begun work, but it was halted in Jan 2020 in favor of other more important work on things like the application and HR portal. 

Our original intent was to have 3 primary blog UIs:
- a post index w/ standard blog filters
- a post page
- a location for admins to publish blogs

Feature-wise, we'd expect:
- the site to be aesthetically similar and contain Talent Cloud's chrome
- recent blogs dynamically showing on the Talent Cloud homepage
- a publishing flow of some sort

**Comment by gobyrne** [comment] 2020-10-29 18:43
Duplicate of #4126

**Closed** 2022-08-11 13:38 UTC
Labels: Front-end, Back-end, Design
