### ISSUE TITLE
Bug - Remove empty links from applicant profile side bar menu

### ISSUE THREAD

**Issue by yonikid15** [GCTC-NTGC/TalentCloud#5456] opened 2021-03-17 14:43 UTC
# Description
There are a some invisible empty links in the applicant profile sidebar menu that still need to be removed, probably lingering from the new changes made. 

# Steps to Reproduce
1. Go to Applicant Profile.
2. Tab through sidebar menu.
3. See error

# Images
![image](https://user-images.githubusercontent.com/22059495/111486047-858f0780-870d-11eb-847a-017ac2584446.png)

**Comment by mnigh** [comment] 2021-03-17 15:16
@yonikid15 I think this is describing the same thing as #5428.

**Comment by tristan-orourke** [comment] 2021-03-17 16:39
Duplicate of #5428

**Closed as completed by tristan-orourke** 2021-03-17 16:39 UTC
Labels: Bug
