### ISSUE TITLE
Feature - Admin - Stop clock on manager portal

### ISSUE THREAD

**Issue by JasmitaChawla** [GCTC-NTGC/TalentCloud#2528] opened 2020-01-08 17:05 UTC
# Description

**Is your feature request related to a problem? Please describe.**
The clock on the review applicants page, on the manager portal, keeps going even after a job process has closed.

**Describe the solution you'd like**
Admins should be able to go in and stop the clock. 

**Describe alternatives you've considered**

# Images

- [ ] This task requires a unit test.
- [ ] This task is complex and needs acceptance criteria.

# Acceptance criteria
- [ ] Requirement one
- [ ] Requirement two
- [ ] Requirement three

**Comment by gobyrne** [comment] 2020-02-06 14:09
Duplicate of #1678 - closing

**Closed by gobyrne** 2020-02-06 14:09 UTC
