### ISSUE TITLE
Manager - Display priorities separately on Review Applicants page

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/TalentCloud#691] opened 2019-02-03 02:19 UTC
# Description
#687 and #690 completed.

Goal is to implement the display of priorities as in this wireframe:
![Home - no tooltip](https://user-images.githubusercontent.com/16977254/55432773-bea23180-5561-11e9-98ee-015000f978bc.png)

**Comment by gggrant** [comment] 2019-04-11 15:50
Duplicate of #873 (complete)

**Closed by gggrant** 2019-04-11 15:50 UTC
Labels: Front-end, Medium Complexity
