### ISSUE TITLE
Remove english_or_french from language requirement options for Job Posts

### ISSUE THREAD

**Issue by xander-miller** [GCTC-NTGC/TalentCloud#796] opened 2019-03-18 14:38 UTC
Remove `english_or_french` from `language_requirements` table in database. Will also recommend refactoring enum options like `language_requirements` out of database and into job post model so they are easier to update and manage.

**Comment by gobyrne** [comment] 2019-03-18 19:20
Duplicate of #799

Description from that issue:
Remove english_or_french from language_requirements table in database. Will also recommend refactoring enum options like language_requirements out of database and into job post model so they are easier to update and manage.

**Closed** 2019-03-18 19:20 UTC
Labels: Back-end, Medium Complexity
