### ISSUE TITLE
Manager - Make first 2 questions standard on all Job posters

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/TalentCloud#530] opened 2018-12-11 21:04 UTC
# Description

Make the following two open ended questions default on all job posters. They should simply be there by default when a "hiring manager" clicks "create new job poster". The hiring manager should still have the option of deleting them.

 - Why are you interested in this job? / Pourquoi êtes-vous intéressé par ce travail?
 - Why do you think you would be a good fit for this job? / Pourquoi pensez-vous que vous serez un bon candidat pour ce poste?

# Required for Completion
Add/remove others as necessary for this specific task.
- [ ] Run Lighthouse (Chrome Dev Tools)
- [ ] Run WAVE Evaluation
- [ ] Browser Compatibility Check
- [ ] Update Translation Spreadsheet
- [ ] Does this affect configuration? (If so discuss with team)
- [ ] Create pull request to `dev`
- [ ] Address issues found during peer review
- [ ] Have someone else accept pull request into `dev`

**Comment by gggrant** [comment] 2019-01-23 13:02
Duplicate of #590

**Closed by gggrant** 2019-01-23 13:02 UTC
Labels: BED, Low Complexity, Prioritized
