### ISSUE TITLE
Applicant - Add word limit to Need to Have skills

### ISSUE THREAD

**Issue by JasmitaChawla** [GCTC-NTGC/TalentCloud#484] opened 2018-11-15 18:28 UTC
Add a word limit in the **Need to Have** skills section so that users have a better idea of how much information is expected. 

<img width="959" alt="screen shot of Skills You Need to Have page" src="https://user-images.githubusercontent.com/38079220/48573330-e312af80-e8d9-11e8-8568-ef60f71e6be2.png">

**Comment by gobyrne** [comment] 2019-01-08 21:03
duplicate of #556

**Closed by gobyrne** 2019-01-08 21:03 UTC
Labels: FED, Task
